#!/usr/bin/env bash
# run-tasks.sh — autonomous task runner for a decompose-prd prd.json.
#
# Loops a FRESH agent instance over the user stories in prd.json until every
# story passes. Each iteration has no memory of the last — which is why stories
# must be sized to one iteration (that is decompose-prd's whole job).
#
# Generated by the decompose-prd skill. Safe to edit. It is NOT run for you —
# you run it when you're ready to execute the tasks.
#
# Config (environment overrides):
#   AGENT_CMD  command that takes a prompt on stdin and runs one agent turn.
#              default: "claude -p". For unattended runs you'll likely want
#              tool permissions handled, e.g.
#                AGENT_CMD="claude -p --permission-mode acceptEdits"
#              or another agent, e.g. AGENT_CMD="amp".
#   PRD        task file (default: prd.json)
#   MAX_ITER   safety cap on iterations (default: 50)
#   VALIDATE   path to decompose-prd's validate.py (default: installed skill);
#              validation is skipped if it isn't found.
set -euo pipefail

AGENT_CMD="${AGENT_CMD:-claude -p}"
PRD="${PRD:-prd.json}"
MAX_ITER="${MAX_ITER:-50}"
VALIDATE="${VALIDATE:-$HOME/.claude/skills/decompose-prd/scripts/validate.py}"
PROGRESS="progress.txt"

[ -f "$PRD" ] || { echo "no $PRD here — run decompose-prd first" >&2; exit 1; }

branch="$(python3 -c "import json;print(json.load(open('$PRD')).get('branchName',''))")"

# On a feature (branchName) change, archive the prior run if it has real
# progress, then point progress.txt at the new feature either way.
if [ -f "$PROGRESS" ]; then
  prev="$(sed -n '1s/^# run: //p' "$PROGRESS")"
  if [ -n "$prev" ] && [ "$prev" != "$branch" ]; then
    if [ "$(wc -l < "$PROGRESS")" -gt 1 ]; then
      dir="archive/$(date +%F)-${prev##*/}"
      mkdir -p "$dir" && cp "$PRD" "$PROGRESS" "$dir"/ 2>/dev/null || true
      echo "archived previous run ($prev) → $dir" >&2
    fi
    printf '# run: %s\n' "$branch" > "$PROGRESS"
  fi
else
  printf '# run: %s\n' "$branch" > "$PROGRESS"
fi

all_pass() {
  python3 -c "import json,sys;d=json.load(open('$PRD'));sys.exit(0 if d.get('userStories') and all(s.get('passes') for s in d['userStories']) else 1)"
}

# id + title of the lowest-priority story still failing (the next target).
target() {
  python3 -c "import json;s=sorted((x for x in json.load(open('$PRD')).get('userStories',[]) if not x.get('passes')),key=lambda x:x.get('priority',0));print(f\"{s[0].get('id','?')}: {s[0].get('title','?')}\" if s else '')"
}

read -r -d '' PROMPT <<'EOF' || true
You are ONE iteration of an autonomous build loop with no memory of prior runs.
The source of truth is prd.json and progress.txt in the current directory.

1. Read prd.json. Pick the lowest-`priority` user story whose `passes` is false.
   If every story already passes, say so and stop without changing anything.
2. Implement exactly that ONE story. Satisfy every item in its
   acceptanceCriteria. Use the skills named in its criteria/notes (for example,
   verify UI changes with the automate-browser skill).
3. Verify: the typecheck — plus any tests or browser checks the criteria call
   for — must actually pass.
4. Only once it genuinely passes: set that story's "passes" to true in prd.json,
   append one line to progress.txt summarising what you did, and commit.
Do not start a second story. Never mark a story passing that you did not verify.
EOF

for ((i = 1; i <= MAX_ITER; i++)); do
  if all_pass; then
    echo "✅ all stories pass — done after $((i - 1)) iteration(s)"
    exit 0
  fi
  if [ -f "$VALIDATE" ]; then
    python3 "$VALIDATE" --in "$PRD" >/dev/null \
      || { echo "⛔ $PRD failed validation — fix it before running" >&2; exit 1; }
  fi
  echo "── iteration $i ──────────────────────────────" >&2
  printf '[%s] iteration %d → %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$i" "$(target)" >> "$PROGRESS"
  printf '%s\n' "$PROMPT" | $AGENT_CMD
done

echo "⚠ hit MAX_ITER=$MAX_ITER without all stories passing" >&2
exit 1
