#!/usr/bin/env python3
"""Render a structured deep-research JSON to one self-contained HTML file
(spec A10).

One concern: turn the JSON payload from SKILL.md Step 6 into a single
dependency-free HTML document — inline CSS, escaped content, light/dark
friendly, citations rendered as clickable links. The markdown path is
handled by Claude directly; this script exists only for the optional HTML.

USAGE
    python3 scripts/report.py [--out=PATH] < research.json

    stdin  = JSON payload (the research object from SKILL.md Step 6)
    stdout = HTML when --out is not given; otherwise a one-line confirm
    --out=PATH  write the HTML to PATH and print "wrote PATH" to stdout
                instead of dumping HTML to stdout

I/O CONTRACT
    stdin  : JSON
    stdout : HTML (default) or "wrote <path>" line (with --out)
    stderr : human diagnostics
    exit   : 0 on success;
             1 on invalid JSON, missing required keys, or write failure

EXPECTED JSON SHAPE
    See references/research-templates.md §1 for the full structure. The
    keys this renderer requires: title, date, type, summary, sections,
    sources. `question`, `depth`, and `open_questions` are optional.

BRACE SAFETY
    User-derived strings (title, summary, section bodies) routinely contain
    literal `{` and `}` — pseudocode, JSON examples, regex. The TEMPLATE-
    level `.format()` call uses `safe()` to HTML-escape AND brace-double
    user content, so research content containing literal `{...}` doesn't
    crash the renderer with a KeyError. Same pattern as generate-prd's
    report.py.
"""

import argparse
import html
import json
import sys
from pathlib import Path

# Outer .format() placeholders: {title} {meta} {question} {summary} {body}
# {sources} {open_q}. Doubled {{ }} inside the CSS are legitimate .format()
# escapes.
TEMPLATE = """<!doctype html>
<meta charset="utf-8">
<title>{title} — deep-research</title>
<style>
  :root {{
    color-scheme: light dark;
    --fg: #111; --muted: #555; --line: #ddd; --bg: #fff;
    --code-bg: #f4f4f5; --link: #2563eb;
  }}
  @media (prefers-color-scheme: dark) {{
    :root {{
      --fg: #e7e7e7; --muted: #9aa0a6; --line: #2a2a2a; --bg: #161616;
      --code-bg: #1f1f1f; --link: #79a8ff;
    }}
  }}
  html, body {{ background: var(--bg); color: var(--fg); }}
  body {{
    font: 15px/1.55 system-ui, -apple-system, "Segoe UI", sans-serif;
    max-width: 800px; margin: 2rem auto; padding: 0 1rem;
  }}
  h1 {{ margin: 0 0 .25rem; font-size: 1.85rem; }}
  h2 {{
    margin: 2rem 0 .5rem; padding-bottom: .2rem;
    border-bottom: 1px solid var(--line); font-size: 1.2rem;
  }}
  h3 {{ margin: 1.25rem 0 .35rem; font-size: 1.0rem; color: var(--muted); }}
  a {{ color: var(--link); }}
  .meta {{ color: var(--muted); font-size: .9rem; margin: 0 0 1.25rem; }}
  .question {{
    border-left: 3px solid var(--line); padding: .35rem .75rem;
    color: var(--muted); margin: 0 0 1rem; font-style: italic;
  }}
  .summary {{ margin: 0 0 2rem; }}
  section p {{ white-space: pre-wrap; margin: .25rem 0 0; }}
  pre, code {{
    background: var(--code-bg); border-radius: 4px;
    font: 13px/1.45 ui-monospace, SFMono-Regular, Menlo, monospace;
  }}
  pre {{ padding: .75rem; overflow-x: auto; }}
  code {{ padding: 0 .25rem; }}
  ol.sources li {{ margin: .25rem 0; }}
  .provider-tag {{
    display: inline-block; padding: 0 .35rem; margin-left: .35rem;
    font-size: .75rem; color: var(--muted); border: 1px solid var(--line);
    border-radius: 3px; vertical-align: 1px;
  }}
  footer {{
    margin-top: 3rem; padding-top: .75rem; border-top: 1px solid var(--line);
    color: var(--muted); font-size: .85rem;
  }}
</style>

<h1>{title}</h1>
<p class="meta">{meta}</p>
{question}
<p class="summary">{summary}</p>

{body}

{open_q}

<h2>Sources</h2>
<ol class="sources">
{sources}
</ol>

<footer>Generated by deep-research.</footer>
"""

PROVIDER_LABEL = {
    "tavily": "Tavily",
    "exa": "Exa",
    "websearch": "WebSearch",
    "webfetch": "WebFetch (full page)",
    "scan-trends": "via /scan-trends",
}


def log(msg):
    print(msg, file=sys.stderr)


def safe_braces(s):
    """Escape `{` and `}` so user content passes through `.format()` literally."""
    return s.replace("{", "{{").replace("}", "}}")


def safe(s):
    """HTML-escape AND brace-double a user-derived string for `.format()`."""
    return safe_braces(html.escape(s))


def render_section(key, body):
    """One <section> per research-type section. Body is markdown-flavored
    free text — we don't fully render markdown; we preserve newlines via
    white-space: pre-wrap in the CSS. The markdown file is the source of
    truth; the HTML is a shareable companion."""
    title = key.replace("_", " ").capitalize()
    text = body or "(not surfaced in sources — see open questions)"
    return (f'<section id="{html.escape(key)}">'
            f'<h2>{html.escape(title)}</h2>'
            f'<p>{safe(text)}</p></section>')


def render_source(i, src):
    """One <li> per source. Provider gets a small muted tag."""
    url = src.get("url") or ""
    title = src.get("title") or url or f"Source {i}"
    provider = src.get("provider", "")
    accessed = src.get("accessed", "")
    label = PROVIDER_LABEL.get(provider, provider) if provider else ""
    bits = []
    if url:
        bits.append(
            f'<a href="{html.escape(url)}" rel="noopener" target="_blank">'
            f'{html.escape(title)}</a>'
        )
    else:
        bits.append(html.escape(title))
    if label:
        bits.append(f'<span class="provider-tag">{html.escape(label)}</span>')
    if accessed:
        bits.append(
            f'<span class="meta"> &middot; accessed {html.escape(accessed)}</span>'
        )
    return f'<li>{"".join(bits)}</li>'


def render_open_questions(items):
    if not items:
        return ""
    lis = "".join(f"<li>{safe(str(q))}</li>" for q in items)
    return f"<h2>Open questions</h2><ul>{lis}</ul>"


def render_question(q):
    if not q:
        return ""
    return f'<p class="question">{safe(str(q))}</p>'


def main():
    ap = argparse.ArgumentParser(add_help=True)
    ap.add_argument("--out")
    args = ap.parse_args()

    try:
        data = json.load(sys.stdin)
    except (ValueError, OSError) as e:
        log(f"FATAL: invalid JSON on stdin ({e.__class__.__name__}: {e})")
        sys.exit(1)

    required = ("title", "date", "type", "summary", "sections", "sources")
    missing = [k for k in required if k not in data]
    if missing:
        log(f"FATAL: missing required keys: {', '.join(missing)}")
        sys.exit(1)

    title = safe(str(data["title"]))
    date = safe(str(data["date"]))
    rtype = safe(str(data["type"]))
    depth = safe(str(data.get("depth", "standard")))
    meta = f"{rtype} research &middot; depth: {depth} &middot; {date}"

    body = "\n\n".join(
        render_section(key, str(val or "")) for key, val in
        (data.get("sections") or {}).items()
    )

    sources = (data.get("sources") or [])
    src_html = "\n".join(
        render_source(i + 1, s) for i, s in enumerate(sources)
    )

    out_html = TEMPLATE.format(
        title=title,
        meta=meta,
        question=render_question(data.get("question")),
        summary=safe(str(data["summary"])),
        body=body,
        sources=src_html,
        open_q=render_open_questions(data.get("open_questions") or []),
    )

    if args.out:
        target = Path(args.out).expanduser()
        try:
            target.write_text(out_html, "utf-8")
        except OSError as e:
            log(f"FATAL: write failed ({e.__class__.__name__}: {e})")
            sys.exit(1)
        print(f"wrote {target}")
    else:
        sys.stdout.write(out_html)


if __name__ == "__main__":
    main()
