#!/usr/bin/env python3
"""
Render a scan-trends run into a self-contained results.html (no external assets).

Input: a JSON object on stdin describing the finished run:
  {
    "topic":        "AI browser agents",
    "query_type":   "RECOMMENDATIONS",
    "window":       "30 days",
    "requested_at": "2026-05-18",          # date the prompt was made
    "mode":         "SCRIPTS",             # optional
    "learned":      [ {"title": "...", "body": "...", "citation": "per r/x"} ],
    "key_patterns": [ "Pattern — per @handle", ... ],
    "stats":        [ "Reddit: 24 threads | 173,316 upvotes | ...", ... ],
    "top_voices":   "r/technology, HN, @handle",   # optional
    "notes":        "Partial run — 3 of 6 sources ..."  # optional
  }

Usage: python3 report.py [--out=PATH]   (default: ./results.html)
Prints the absolute path written.
"""
import sys, os, json, html
from datetime import datetime


def esc(x):
    return html.escape(str(x if x is not None else ""))


def parse_args(argv):
    out = "results.html"
    for a in argv[1:]:
        if a.startswith("--out="):
            out = a.split("=", 1)[1] or out
    return out


CSS = """
:root{--bg:#f6f7f9;--card:#fff;--ink:#1a1c1f;--mut:#6b7280;--line:#e5e7eb;
--accent:#4f46e5;--accent-soft:#eef2ff}
@media(prefers-color-scheme:dark){:root{--bg:#0f1115;--card:#181b21;
--ink:#e8eaed;--mut:#9aa1ab;--line:#2a2e37;--accent:#8b8cf9;--accent-soft:#1e2030}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);
font:16px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif}
.wrap{max-width:820px;margin:0 auto;padding:48px 24px 80px}
h1{font-size:28px;margin:0 0 4px;letter-spacing:-.01em}
.sub{color:var(--mut);font-size:14px;margin-bottom:20px}
.badges{display:flex;flex-wrap:wrap;gap:8px;margin:16px 0 28px}
.badge{background:var(--accent-soft);color:var(--accent);font-size:12px;
font-weight:600;padding:5px 11px;border-radius:999px;border:1px solid var(--line)}
h2{font-size:13px;text-transform:uppercase;letter-spacing:.08em;color:var(--mut);
margin:36px 0 14px;font-weight:700}
.card{background:var(--card);border:1px solid var(--line);border-radius:12px;
padding:18px 20px;margin-bottom:12px}
.card .t{font-weight:700;margin-bottom:6px}
.card .c{color:var(--mut);font-size:13px;font-style:italic;margin-top:8px}
ol{padding-left:20px;margin:0}ol li{margin:8px 0}
.stats{background:var(--card);border:1px solid var(--line);border-radius:12px;
padding:8px 20px}.stats div{padding:9px 0;border-bottom:1px solid var(--line);
font-size:14px}.stats div:last-child{border-bottom:0}
.note{background:var(--accent-soft);border:1px solid var(--line);border-radius:10px;
padding:12px 16px;font-size:14px;color:var(--ink);margin-bottom:20px}
.foot{margin-top:48px;padding-top:18px;border-top:1px solid var(--line);
color:var(--mut);font-size:12px}
"""


def build_html(d):
    topic = esc(d.get("topic", "scan-trends"))
    badges = []
    for k in ("query_type", "window", "mode"):
        if d.get(k):
            badges.append(f'<span class="badge">{esc(d[k])}</span>')
    badges_html = "".join(badges)

    learned = ""
    for item in d.get("learned", []) or []:
        cite = item.get("citation")
        learned += (
            '<div class="card"><div class="t">' + esc(item.get("title", "")) +
            '</div><div>' + esc(item.get("body", "")) + '</div>' +
            (f'<div class="c">{esc(cite)}</div>' if cite else "") + '</div>'
        )
    if not learned:
        learned = '<div class="card"><div>No findings recorded.</div></div>'

    kp = "".join(f"<li>{esc(p)}</li>" for p in (d.get("key_patterns") or []))
    kp_html = f"<h2>Key patterns</h2><ol>{kp}</ol>" if kp else ""

    stats = "".join(f"<div>{esc(s)}</div>" for s in (d.get("stats") or []))
    if d.get("top_voices"):
        stats += f'<div>Top voices: {esc(d["top_voices"])}</div>'
    stats_html = f'<h2>Sources</h2><div class="stats">{stats}</div>' if stats else ""

    note_html = (f'<div class="note">{esc(d["notes"])}</div>'
                 if d.get("notes") else "")
    req = esc(d.get("requested_at", ""))
    gen = datetime.now().strftime("%Y-%m-%d %H:%M")

    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>scan-trends — {topic}</title><style>{CSS}</style></head><body><div class="wrap">
<h1>{topic}</h1>
<div class="sub">Prompt requested: {req}</div>
<div class="badges">{badges_html}</div>
{note_html}
<h2>What I learned</h2>
{learned}
{kp_html}
{stats_html}
<div class="foot">Generated by scan-trends · {gen}</div>
</div></body></html>"""


def main():
    out = parse_args(sys.argv)
    try:
        data = json.load(sys.stdin)
    except Exception as e:
        print(f"[report] invalid JSON on stdin: {e}", file=sys.stderr)
        sys.exit(1)

    path = os.path.abspath(os.path.expanduser(out))
    try:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(build_html(data))
    except OSError as e:
        print(f"[report] could not write {path}: {e}", file=sys.stderr)
        sys.exit(1)

    print(f"[report] wrote {path}", file=sys.stderr)
    print(path)


if __name__ == "__main__":
    main()
