#!/usr/bin/env python3
"""Render a structured PRD JSON to one self-contained HTML file (spec A10).

One concern: turn the JSON payload from SKILL.md Step 4 into a single
dependency-free HTML document — inline CSS, escaped content, light/dark
friendly. The markdown path is handled by Claude directly; this script
exists only to produce the optional HTML companion.

USAGE
    python3 scripts/report.py [--out=PATH] < prd.json

    stdin  = JSON payload (the PRD object from SKILL.md Step 4)
    stdout = HTML when --out is not given; otherwise a one-line confirm
    --out=PATH  write the HTML to PATH and print "wrote PATH" to stdout
                instead of dumping HTML to stdout

I/O CONTRACT
    stdin  : JSON
    stdout : HTML (default) or "wrote <path>" line (with --out)
    stderr : human diagnostics
    exit   : 0 on success;
             1 on invalid JSON, missing required keys, or write failure

EXPECTED JSON SHAPE
    {
      "title": "...",
      "slug": "kebab",
      "date": "YYYY-MM-DD",
      "summary": "...",
      "discussion_source": "in-session" | "transcript:<path>",
      "sections": {
        "problem":                "...",
        "solution":               "...",
        "ux_flow":                "...",
        "technical_architecture": "...",
        "data_model":             "...",
        "pricing":                "...",
        "roadmap":                "...",
        "risks":                  "...",
        "open_questions":         "..."
      }
    }

BRACE SAFETY
    User-derived strings (title, summary, section bodies) routinely contain
    literal `{` and `}` — pseudocode, JSON examples, template placeholders.
    Both the TEMPLATE-level `.format()` call AND the inner per-section
    interpolation pre-double braces in user input via `safe_braces()` so
    `.format()` treats them as literal characters rather than placeholder
    lookups. Without this, a section containing `{user.name}` or `{"foo": 1}`
    would raise `KeyError` and crash the renderer.
"""

import argparse
import html
import json
import sys
from pathlib import Path

# Ordered list — also defines the rendering order in the HTML.
SECTIONS = [
    ("problem",                "Problem"),
    ("solution",               "Solution"),
    ("ux_flow",                "UX flow"),
    ("technical_architecture", "Technical architecture"),
    ("data_model",             "Data model"),
    ("pricing",                "Pricing"),
    ("roadmap",                "Roadmap"),
    ("risks",                  "Risks"),
    ("open_questions",         "Open questions"),
]

# Outer .format() placeholders: {title} {date} {source} {summary} {body}.
# Doubled {{ }} inside the CSS are legitimate .format() escapes.
TEMPLATE = """<!doctype html>
<meta charset="utf-8">
<title>{title} — PRD</title>
<style>
  :root {{
    color-scheme: light dark;
    --fg: #111; --muted: #555; --line: #ddd; --bg: #fff; --code-bg: #f4f4f5;
  }}
  @media (prefers-color-scheme: dark) {{
    :root {{
      --fg: #e7e7e7; --muted: #9aa0a6; --line: #2a2a2a; --bg: #161616;
      --code-bg: #1f1f1f;
    }}
  }}
  html, body {{ background: var(--bg); color: var(--fg); }}
  body {{
    font: 15px/1.55 system-ui, -apple-system, "Segoe UI", sans-serif;
    max-width: 760px; margin: 2rem auto; padding: 0 1rem;
  }}
  h1 {{ margin: 0 0 .25rem; font-size: 1.75rem; }}
  h2 {{
    margin: 2rem 0 .5rem; padding-bottom: .2rem;
    border-bottom: 1px solid var(--line); font-size: 1.15rem;
  }}
  .meta {{ color: var(--muted); font-size: .9rem; margin: 0 0 1.5rem; }}
  .summary {{
    border-left: 3px solid var(--line); padding: .35rem .75rem;
    color: var(--muted); margin: 0 0 2rem;
  }}
  section p {{ white-space: pre-wrap; margin: .25rem 0 0; }}
  pre, code {{
    background: var(--code-bg); border-radius: 4px;
    font: 13px/1.45 ui-monospace, SFMono-Regular, Menlo, monospace;
  }}
  pre {{ padding: .75rem; overflow-x: auto; }}
  code {{ padding: 0 .25rem; }}
  footer {{
    margin-top: 3rem; padding-top: .75rem; border-top: 1px solid var(--line);
    color: var(--muted); font-size: .85rem;
  }}
</style>

<h1>{title}</h1>
<p class="meta">PRD · {date} · synthesized from {source}</p>
<p class="summary">{summary}</p>

{body}

<footer>Generated by generate-prd.</footer>
"""


def log(msg):
    print(msg, file=sys.stderr)


def safe_braces(s):
    """Escape `{` and `}` so user content passes through `.format()` literally.

    See module docstring "BRACE SAFETY".  Apply this to any string that
    contains user input before it reaches `.format()`.
    """
    return s.replace("{", "{{").replace("}", "}}")


def safe(s):
    """HTML-escape AND brace-double a user-derived string for `.format()`."""
    return safe_braces(html.escape(s))


def render_section(key, label, value):
    """One <section> per PRD section, fully escaped + brace-safe."""
    text = value if isinstance(value, str) else json.dumps(value, indent=2)
    text = text or "(not discussed — see open questions)"
    return (f'<section id="{html.escape(key)}">'
            f'<h2>{html.escape(label)}</h2>'
            f'<p>{safe(text)}</p></section>')


def main():
    ap = argparse.ArgumentParser(add_help=True)
    ap.add_argument("--out")
    args = ap.parse_args()

    try:
        data = json.load(sys.stdin)
    except (ValueError, OSError) as e:
        log(f"FATAL: invalid JSON on stdin ({e.__class__.__name__}: {e})")
        sys.exit(1)

    required = ("title", "date", "summary", "sections")
    missing = [k for k in required if k not in data]
    if missing:
        log(f"FATAL: missing required keys: {', '.join(missing)}")
        sys.exit(1)

    sections = data.get("sections", {}) or {}
    body = "\n\n".join(
        render_section(key, label, sections.get(key, ""))
        for key, label in SECTIONS
    )

    out_html = TEMPLATE.format(
        title=safe(str(data["title"])),
        date=safe(str(data["date"])),
        source=safe(str(data.get("discussion_source", "—"))),
        summary=safe(str(data["summary"])),
        body=body,  # already fully escaped + brace-safe via render_section
    )

    if args.out:
        target = Path(args.out).expanduser()
        try:
            target.write_text(out_html, "utf-8")
        except OSError as e:
            log(f"FATAL: write failed ({e.__class__.__name__}: {e})")
            sys.exit(1)
        print(f"wrote {target}")
    else:
        sys.stdout.write(out_html)


if __name__ == "__main__":
    main()
